// JDTools - Patch conversion utility for Roland JD-800 / JD-990
// 2022 - 2024 by Johannes Schultz
// License: BSD 3-clause

#pragma once

static constexpr const char *WaveformNames[] =
{
	"None",
	"Syn Saw 1",
	"Syn Saw 2",
	"FAT Saw",
	"FAT Square",
	"Syn Pulse1",
	"Syn Pulse2",
	"Syn Pulse3",
	"Syn Pulse4",
	"Syn Pulse5",
	"Pulse Mod",
	"Triangle",
	"Syn Sine",
	"Soft Pad",
	"Wire Str",
	"MIDI Clav",
	"Spark Vox1",
	"Spark Vox2",
	"Syn Sax",
	"Clav Wave",
	"Cello Wave",
	"BrightDigi",
	"Cutters",
	"Syn Bass",
	"Rad Hose",
	"Vocal Wave",
	"Wally Wave",
	"Brusky lp",
	"Digiwave",
	"Can Wave 1",
	"Can Wave 2",
	"EML 5th",
	"Wave Scan",
	"Nasty",
	"Wave Table",
	"Fine Wine",
	"Funk Bass1",
	"Funk Bass2",
	"Strat Sust",
	"Harp Harm",
	"Full Organ",
	"Full Draw",
	"Doo",
	"ZZZ Vox",
	"Org Vox",
	"Male Vox",
	"Kalimba",
	"Xylo",
	"Marim Wave",
	"Log Drum",
	"AgogoBells",
	"Bottle Hit",
	"Gamelan 1",
	"Gamelan 2",
	"Gamelan 3",
	"Tabla",
	"Pole lp",
	"Pluck Harp",
	"Nylon Str",
	"Hooky",
	"Muters",
	"Klack Wave",
	"Crystal",
	"Digi Bell",
	"FingerBell",
	"Digi Chime",
	"Bell Wave",
	"Org Bell",
	"Scrape Gut",
	"Start Atk",
	"Hellow Bs",
	"Piano Atk",
	"EP Hard",
	"Clear Keys",
	"EP Distone",
	"Flute Push",
	"Shami",
	"Wood Crak",
	"Klmba Atk",
	"Block",
	"Org Atk 1",
	"Org Atk 2",
	"Cowbell",
	"Sm Metal",
	"StrikePole",
	"Pizz",
	"Switch",
	"Tuba Slap",
	"Plink",
	"Plunk",
	"EP Atk",
	"TVF_Trig",
	"Flute Tone",
	"Pan Pipe",
	"BottleBlow",
	"Shaku Atk",
	"FlugelWave",
	"French",
	"WhiteNoise",
	"Pink Noise",
	"Pitch Wind",
	"Vox Noise1",
	"Vox Noise2",
	"CrunchWind",
	"ThroatWind",
	"Metal Wind",
	"Windago",
	"Anklungs",
	"Wind Chime",
	"Ac Piano 1",
	"SA Rhodes 1",
	"SA Rhodes 2",
	"E.Piano 1",
	"E.Piano 2",
	"Clav 1",
	"Organ 1",
	"Jazz Organ",
	"Pipe Organ",
	"Nylton GTR",
	"6STR GTR",
	"GTR HARM",
	"Mute GTR 1",
	"Pop Strat",
	"Stratus",
	"SYN GTR",
	" Harp 1",
	"Pick Bass",
	"E.Bass",
	"Fretless 1",
	"Upright BS",
	"Slap Bass 1",
	"Slap & Pop",
	"Slap Bass 2",
	"Slap Bass 3",
	"Flute 1",
	"Trumpet 1",
	"Trombone 1",
	"Harmon Mute1",
	"Alto Sax 1",
	"Tenor Sax 1",
	"Blow Pipe",
	"Trumpet SECT",
	"Strings",
	"SYN VOX 1",
	"SYN VOX 2",
	"Org Vox 2",
	"Pop Voice",
	"Fantasynth",
	"Fanta Bell",
	"Vibes",
	"Steel Drums",
	"MMM Vox",
	"Lead Wave",
	"Feedbackwave",
	"Rattles",
	"Tin Wave",
	"Spectrum 1",
	"Solid Kick",
	"Room Kick",
	"808 K Long",
	"Hard SN",
	"808 SN",
	"90's SN",
	"Bigshot SN",
	"Power SN",
	"Power Tom",
	"Closed HH1",
	"Closed HH2",
	"Open HH",
	"Crash Cym",
	"Ride Cym",
	"808 Claps",
	"Maraca",
	"Cabasa Up",
	"CabasaDown",
	"Slpa Cga",
	"Mute Cga 1",
	"Mute Cga 2",
	"Hi Conga",
	"Lo Conga",
	"Snaps",
	"Tambourine",
	"Cowbell 2",
	"Saw +DC",
	"Sqr +DC",
	"Pulse1 +DC",
	"Pulse2 +DC",
	"Pulse3 +DC",
	"Pulse4 +DC",
	"Pulse5 +DC",
	"Triangle +DC",
	"Sine +DC",
	"Loop 1",
	"Loop 2",
	"Loop 3",
	"Loop 4",
};
